[build]
  base = "/"
  command = "npm run build" 
  publish = "/src/public" 

[functions]
  external_node_modules = ["express", ]
  node_bundler = "esbuild"
  included_files = ["src/views/email/**"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

